- name: Deploy manifests in k8s cluster
  hosts: localhost
  tasks: 
  - name: Login to docker locally to create .dockerjson config file
    community.docker.docker_login:
      username: "{{ docker_user }}"
      password: "{{ docker_pass }}"
  - name: Create docker registry secret
    kubernetes.core.k8s:
      state: present
      kubeconfig: ~/.kube/config
      definition:
        apiVersion: v1
        kind: Secret
        metadata:
          name: my-registry-key
          namespace: default
        type: kubernetes.io/dockerconfigjson
        data:
          .dockerconfigjson: "{{ lookup('file', '~/.docker/config.json' ) | b64encode }}"
  
  - name: Add ingress-nginx repository 
    kubernetes.core.helm_repository:
      name: ingress-nginx
      repo_url: https://kubernetes.github.io/ingress-nginx
      kubeconfig: ~/.kube/config
  - name: Deploy nginx ingress controller
    kubernetes.core.helm:
      name: ingress-controller
      chart_ref: ingress-nginx/ingress-nginx
      release_namespace: ingress
      create_namespace: true

  - name: Add Bitnami repository
    kubernetes.core.helm_repository:
      name: bitnami 
      repo_url: https://charts.bitnami.com/bitnami
      kubeconfig: ~/.kube/config
  - name: Deploy Mysql chart with 3 replicas
    kubernetes.core.helm:
      name: mysql-release
      chart_ref: bitnami/mysql
      release_namespace: default
      values: "{{ lookup('template', 'k8s-deployment/mysql-chart-values-eks.yaml') | from_yaml }}"

