--- 
- name: Deploy manifest in k8s cluster 
  hosts: localhost
  tasks:
  - name: Login to docker to create .dockerjson config file
    community.docker.docker_login:
      registry_url: https://index.docker.io/v1/
      username: "{{ docker_user }}"
      password: "{{ docker_pass }}"
  - name: Create docker registry secret 
    kubernetes.core.k8s:
      state: present 
      definition:
        apiVersion: v1
        kind: Secret 
        type: kubernetes.io/dockerconfigjson
        metadata:
          name: my-registry-key
          namespace: default
        data: 
          .dockerconfigjson: "{{ lookup('file', '~/.docker/config.json' ) | b64encode }}"