--- 
- name: Deploy manifest in k8s cluster 
  hosts: localhost
  tasks:
  - name: Login to docker to create .dockerjson config file
    community.docker.docker_login:
      registry_url: https://index.docker.io/v1/
      username: "{{ docker_user }}"
      password: "{{ docker_pass }}"
  - name: Create docker registry secret 
    kubernetes.core.k8s:
      state: present
      kubeconfig: ~/.kube/config
      definition:
        apiVersion: v1
        kind: Secret 
        type: kubernetes.io/dockerconfigjson
        metadata:
          name: my-registry-key
          namespace: default
        data: 
          .dockerconfigjson: "{{ lookup('file', '~/.docker/config.json' ) | b64encode }}"
  
  #- name: Add nginx ingress controller repo 
    #kubernetes.core.helm_repository:
      #name: ingress-nginx
      #repo_url: https://kubernetes.github.io/ingress-nginx
      #kubeconfig: ~/.kube/config
 # - name: Deploy nginx ingress controller
  #  kubernetes.core.helm:
  #    name: ingress-controller
     # release_namespace: ingress
     # create_namespace: true
     # chart_ref: ingress-nginx/ingress-nginx
