- name: Deploy manifests in k8s cluster
  hosts: localhost
  tasks: 
  - name: Login to docker locally to create .dockerjson config file
    community.docker.docker_login:
      username: "{{ docker_user }}"
      password: "{{ docker_pass }}"
