apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: db-secret
spec:
  encryptedData:
    db_name: AgBM9ZIpuIzb8eMdjvkogI1yjFmlpUwYWlGhUZFA64isqLIyHGy2Wwml14sbP4l6N5aEBcoQAOKBF+AJQeD3OHK43wNeZ8XMHBd9vWAsu27rnVgDv56xB4hPjq1L10+nHhLqc24r8uw/YnjNQ4emerGzPBLmFnrfSS5ddyETb+SpfxPdR8COFBj6lSrLAAE7dwaeSdpGhV0x14zHUI7iA4LeTYpn1ww4oXYMz1SDJHD0w/83bzJ00VnJxB4I/mVfVPnl/29SpBKCFrwPPi2mbBulET2BAYmWlbngcgiExDTceDGG0RLcYonAbOWYVwJZNIHOvRRDtnGKbSYpzjnIduW+FFlsoj027Iy1k2xA5TOS+dJL0MhC/WKko2QeX+NWIPoNa3IudBXq5degcDv+BebSk4wDoB0uvrKk6gOR4Htgoa3Efr5en2aCCOWfI0d09RV/xdaeHcIEYQDCqO2mdC64nMi7/d5EJomnYdhJy7riK1wJoYmplHxbslU5sxPjjrtO/fYCInLRC8jfNfMu+Ojks1/rYtHZLZKI/MT0tV8C7/8V40aOJUaTpqD9KtjNxSWG77f9S8lEMXm1zJ++2M4GdJPWhzTB7ACyZyY/YCU4jUm4LbO/bNLWP4m7gE/gTCqz5AYGWlQJA0p9Dypx/DHc4x7ZUv4URg+82A12RvwtMed26VFcgHlRDM8ZDGI7CyIu8s6VTHIfetk=
    db_pwd: AgCtDw4EZyB+njx5/6WZQPUgrMbl46NIz+TVFSMpgh92kEyt2vEkVNTif0Frj/IMiiolbLEtMNvL9RUmTSswCbzmpdA7wbpvM+DWpG69FHMFyhMWk4KDzhhnsa5aN7/o88bmcXbIHy40CHWMrcKd3VsUsABdrfGTRWRHnOGc/Y9BosPGhf0mzAxDSqZOm9UPq0n12ORgv8dnfSpFCaU2GvTyJNEUf5/PA7xDWYUGseAEO1msArvqzDKazVgnYJ7b2zKq1jnfZex05ZH7goXm0i8sGjQRrghlasHGzrngqhkAw19K7ybyQMzheVpDszdRsmnRfHulBLXsAXT8hQe6nKqIIr3UAJqlcOeqfRXoE3khcxBh+ZCLNvqI0CNjagt39U1Vwr2P6/2dBGC1gP6qXvrSVrgAcbs9Kbr66kCymZOyDflUzD8qzpI4ZlCj6jR6MuHcHzKZ5mAfbT2vNfnzR/WNkYyLfpS5IIfynXsoHGh/d7cabIAHj3kwHzkKsMFIReNU6VprKujfzbeWF5w/yXYjNvjiMnUZ0HYx3047oal8aqIkomCQtRNe7F1RBiYI5nU0su8eZXFvXEiRxJC9gylIs2gaU3fUXNsaRHx0yPlfqGVtcQsyShe5+biZ3shCqnsuppdUzCR2STOCjLftj2pdPSCF4WA6XYBnS4aeuVSAEfJ7ojrNWCEWpIKdw7UhGDJSRKAZe8HH
    db_root_pwd: AgB/VJMy2sQHt0S9SDlvlKUGYCxNevE6XqVJt1jcm+xtawaGAg6Xn87gv281n/uwy5xX1LL7f3DUXBJZLFTDLb4biWXrqLFn+MFInK/oOOIIQy4+VF09SpoZZl4DYvkne0XoMXnpME13QYbOnwAj7BBv5dHCl1ZJqv18n3uqr+LaBGh5/UsyhV4uTj3N0zO/3sEQEV7bwcmZvn4iM7RmEgBvdlQzvtILTKKR66ClR4HXz2INps1raDX/nJ4AitFEXXOBK0abYmV/1mDZt4Mwj6VUTEWyhNGPAkJYNyYi9Wra5AQ4gieA2hoTrKZgXNeBxIZR698lC6711+HUevJUkNt5j17A1o/JF6uUbHd+9ZuYTEKuH87pd1UCDtt/nrsLd+o50zozBO5bXjWMX5G3Xhe++v2QAhhBInc58D2/Z41l6hE2zSgvH46o4ANEBQvsshfvciIunBKz2AlIdB13Tlf+F6F2gSjTsKoSdZY+m/LvLgKv/wbYLTQIiBMaTgkn140Cz53tbdtMB8s0XP6aDd/eoKNIfz6mgfvE8XTx9uxT13yoWhzvondbnvd1mYHDVS9xkuwfYdus5ds+kwsIC2ZDcWk5PVENmp8Aq6wz1BNraXISEjpzEXeUYnQCctSnJOawC2b4Wl/xk/EyzPnnKxhjMXAjW0+kxt6fsRnoNvNZhXUYqraOSkKAj9+J3qF9IuWswqNvk3nhlVotkpzUZUN+
    db_user: AgAFv70CnS+2InHp7jmrX/5y2MVOwlD/IoUq/F8LukFXQh+b9dp8tAUmrQReBYQpRdWmdEjWR7U+4Bs4AWFdVgp26xon58UFduVMy+gY8mRWjr1mwEOLplWvEGIhM4BPFdgY7/wPUnJprMhnNTgb39RyqqjWq17zH0ry6/QkZhRlDFw7QckfYeJ/MoZfarhCHMYUJIyc58Kt6a/Jpn0Y31KKO/hfi6QvtKA6LLz+cHNHOeZGYqrjsdEmBsK82vyCdkLge4DUIQ64k22QiE6wvRokSshdXHOyy8gsbJkRixDdWw6RoEQZ0hyaXU3HQES5PT0B5ExPTOTTe6D0vu0B+X5IgFh2Q8J2mWQZm4kaYJMMLsveGqsGAmVCJEQqK9MHVusuOmN2tF65hDzIM8Kj4dhGDtYlRxXqSaHcOW09wxEbUyyYfFaQmA6rULHnZijZa8zChmcxqd4PQ1DhIj10qxtYthFHcwYWQkW5QNb9XHra1AuGHvh52ZhSqDUy4nBzS3rZLPyz9+hlJ9VNZhVsAQ7SL8AW/7c9HBDNcTMoWCN+aKEC3XajYbZbx5u/gICyy9nLnrK8q+vLxV+CFGZh3sVCP4Wv4SnVoOERIUNLs5+rVVGv0vf4doCfq1yDs+kjFXPqFL+36yqpwuy4vMhJE3n+CCCw3tOlQ4gFxwy+h3dFwQqRdGjFhA8whmrrQICY1eYaEmZbxkvS
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: db-secret
    type: Opaque


# helm repo add sealed-secrets https://bitnami-labs.github.io/sealed-secrets
# helm install sealed-secrets -n kube-system --set-string fullnameOverride=sealed-secrets-controller sealed-secrets/sealed-secrets

# kubectl get all -n kube-system | grep -i sealed
# kubectl get secret -n kube-system | grep -i sealed

# Install kubeseal
# curl -OL "https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.23.0/kubeseal-0.23.0-linux-amd64.tar.gz"
# tar -xvzf kubeseal-0.23.0-linux-amd64.tar.gz kubeseal
# sudo install -m 755 kubeseal /usr/local/bin/kubeseal

# Create secret file
# sudo vim db-secret.yaml

# kubectl -n kube-system get secrets
# kubectl -n kube-system get secrets <Secret-name> -o yaml
# kubectl -n kube-system get secrets sealed-secrets-keyd5dvq -o json | jq .data'."tls.crt"'
# kubectl -n kube-system get secrets sealed-secrets-keyd5dvq -o json | jq .data'."tls.crt"' -r
# kubectl -n kube-system get secrets sealed-secrets-keyd5dvq -o json | jq .data'."tls.crt"' -r | base64 -d
# kubectl -n kube-system get secrets sealed-secrets-keyd5dvq -o json | jq .data'."tls.crt"' -r | base64 -d > sealedSecret.crt
# cat sealedSecret.crt
# kubeseal --cert sealedSecret.crt --scope cluster-wide < db-secret.yaml
# kubeseal -o yaml --cert sealedSecret.crt --scope cluster-wide < db-secret.yaml > secret.yaml
# cat secret.yaml
# kubectl get secrets