apiVersion: v1
kind: Secret 
metadata:
  name: db-secret
type: Opaque
data:
  db_user: bXktdXNlcg== #my-user
  db_pwd: bXktcGFzcw== #my-pass
  db_name: bXktYXBwLWRi #my-app-db
  db_root_pwd: c2VjcmV0LXJvb3QtcGFzcw== #secret-root-pass