apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app-deployment
  labels:
    app: java-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
      - name: java-app
        image: chinmayapradhan/java-mysql-app:1.0
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: db_user
        - name: DB_PWD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: db_pwd
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: db_name
        - name: DB_SERVER
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: db_server
            
--- 
apiVersion: v1
kind: Service
metadata:
  name: java-app-service
spec:
  selector:
    app: java-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080