apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: k8s-rule
  labels:
    app: kube-prometheus-stack
    release: monitoring-stack
spec:
  groups:
  - name: k8s.rules
    rules:
    - alert: KubernetesStatefulsetDown
      expr: (kube_statefulset_status_replicas_ready / kube_statefulset_status_replicas_current) != 1
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: Kubernetes StatefulSet down (instance {{ $labels.instance }})
        description: "A StatefulSet went down\n VALUE = {{ $value }}\n LABELS = {{ $labels }}"
    - alert