apiVersion: apps/v1
kind: Deployment
metadata:
  name: $APP_NAME-deployment
  namespace: $APP_NAMESPACE
  labels:
    app: $APP_NAME
spec:
  replicas: 3
  selector:
    matchLabels:
      app: $APP_NAME
  template:
    metadata:
      labels:
        app: $APP_NAME
    spec:
      imagePullSecrets:
      - name: my-ecr-registry-key
      containers:
      - name: $APP_NAME
        image: ${IMAGE_NAME}:${IMAGE_TAG}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              key: db_user
              name: db-secret
        - name: DB_PWD
          valueFrom:
            secretKeyRef:
              key: db_pwd
              name: db-secret
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              key: db_name
              name: db-secret
        - name: DB_SERVER
          valueFrom:
            configMapKeyRef:
              key: db_server
              name: db-config
---
apiVersion: v1
kind: Service
metadata:
  name: $APP_NAME-service
  namespace: $APP_NAMESPACE
spec:
  selector:
    app: $APP_NAME
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
